version: "3.8"
services:
    backend:
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        extra_hosts:
            - "host.docker.internal:host-gateway"
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/backend/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - db
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - backend
    db:
        image: postgres:14.4
        restart: unless-stopped
        tty: true
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: laravel_react
        volumes:
            - pgdata:/var/lib/postgresql/data
    redis:
        image: redis:7.0.4
        restart: unless-stopped
        tty: true
        ports:
            - "6379:6379"
        command: redis-server --save 20 1 --loglevel warning
        volumes:
            - cache:/data
    node:
        build:
            context: .
            dockerfile: ./docker/nodejs/Dockerfile
        tty: true
        restart: always
        ports:
            - "5173:5173"
        working_dir: /var/www
        volumes:
            - .:/var/www
    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - "8080:8080"
volumes:
    pgdata:
        driver: local
    cache:
        driver: local
    node_modules:
        driver: local
